#string methods
str1 = 'heLLo haRRy bhai \n'
print(str1.upper())
print(str1.lower())
print(str1.strip())
print(str1.rstrip())
print(str1.lstrip())
print(str1.replace('hello','python'))
print(str1.split('harry'))
print(str1.capitalize())
print(len(str1))
print(str1.center(50))
print(str1.center(50,"*"))
print(str1.count('r'))
print(str1.endswith('...'))
print(str1.startswith('h'))
#find the letter then return index
print(str1.find('y'))
print(str1.index('bhai'))
print(str1.isalpha())
print(str1.isalnum())
print(str1.islower())
print(str1.isupper())
print(str1.isprintable())
print(str1.isspace())
print(str1.title())
print(str1.istitle())
print(str1.swapcase())